name: ip2asn_$(Build.BuildId)

on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '0 0 * * 1'  # Weekly run of the ip2asn extractor script

jobs:
  ip2asn_run:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      # Step 2: Run the script
      - name: Run script
        run: |
          chmod +x ip2asn.sh
          ./ip2asn.sh

      # Step 3: Configure Git and commit changes
      - name: Commit and push changes
        run: |
          # Configure Git
          git config --global user.email "walid.loutfi@outlook.com"
          git config --global user.name "w4l1dcode"

          # Checkout the 'main' branch
          git checkout main

          # Commit the changes if there are any
          git add ip2asn_data/ip2asn-v4.tsv
          git commit -m "Updated ip2asn-v4.tsv" || echo "No changes to commit"

          # Push the changes to the 'main' branch
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
