name: ip2asn_$(Build.BuildId)

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1'  # Weekly run every Monday

jobs:
  ip2asn_run:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub's default token for pulling the repository

      # Step 2: Run the ip2asn script
      - name: Run ip2asn extraction script
        run: |
          chmod +x ip2asn.sh
          ./ip2asn.sh

      # Step 3: Configure Git for commit
      - name: Configure Git
        run: |
          git config --global user.email "walid.loutfi@outlook.com"
          git config --global user.name "w4l1dcode"
          
      # Step 4: Checkout 'main' branch and make changes
      - name: Checkout and Commit Changes
        run: |
          git checkout main  # Ensure we're on the correct branch
          git add ip2asn_data/ip2asn-v4.tsv
          git commit -m "Updated ip2asn-v4.tsv"

      # Step 5: Authenticate using the personal access token 'ip2asn_auth'
      - name: Setup Git authentication
        run: |
          git config --global url."https://x-access-token:${{ secrets.ip2asn_auth }}@github.com".insteadOf "https://github.com"
      
      # Step 6: Push changes to GitHub using the authenticated token
      - name: Push changes to GitHub
        run: |
          git push origin main

