name: ip2asn_$(Build.BuildId)

on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '0 0 * * 1'
      displayName: 'Weekly run of the ip2asn extractor script'
      branches:
        include:
          - main
      always: true

jobs:
  run:
    name: Download + extract ip2asn mapping data
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      # Run the extraction script
      - name: Run ip2asn extraction script
        run: |
          chmod +x ip2asn.sh
          ./ip2asn.sh
        displayName: 'Run script'

      # Configure Git and commit changes
      - name: GIT commit and push ip2asn-v4.tsv
        env: 
          CI_COMMIT_MESSAGE: "Updated ip2asn-v4.tsv"
          CI_COMMIT_AUTHOR: "CI Bot"
        run: |
          # Configure Git
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          
          # Add the new file
          git add ip2asn_data/ip2asn-v4.tsv
          
          # Commit the changes
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          
          # Push changes to the main branch
          git push
        displayName: 'Commit and Push Changes to GitHub'
